public with sharing class Carro {
    public Carro() {
        
        public static Boolean ligarCarro{Boolean ligarcarro}{
            Boolean carroLigado = ligarCarro ? true : false;
            
            if(ligarCarro == true){
                System.debug('ligou o carro');
            } else {
                system.debug('desligou o carro');
            }
        }

    }
public static Boolean ligarFarois(Boolean ligarFarois){
    Boolean igouFarois = ligouFarois ? true : false;
    

}

}
