public with sharing class Desafios {
    public Desafios() {

//1 - DESAFIO - Montar um método que busque e retorne uma lista com todas as oportunidade com a faze igual  'Closed Won'

// 2 - DESAFIO - criar um método que recebe um nome de uma pessoa, e imprima com o system debug 'Olá NOME'

// 3 - DESAFIO - Receber o sobrenome e o nome da empresa e vamos inserir um Lead, o método deve retornar o Id do lead inserid

// 4 - DESAFIO
    //Construir um método que receba dois parâmetros do tipo Inteiro e retorne o a soma destes dois parâmetros
    //Se o parâmetro 1 for maior do 5 deve somar mais dois neste resultado

// 5 - DESAFIOS
    //1 - Buscar e retornar o valor total das oportunidade que a fases não sejam 'Closed Won' e 'Closed Lost'

     //2 - Criar 10 contas com o nome 'Conta 1', 'Conta 2', e assim por diante. Não retornar nada

// 6 - DESAFIO - Receber um número inteiro no parâmetro, e vão criar as contas conforme este número com o nome 'Conta DESAFIO 1', 'Conta DESAFIO 2';


//7 - DESAFIO - Receber um número inteiro no parâmetro, e vão criar as contas conforme este número com o nome 'Conta DESAFIO 1', 'Conta DESAFIO 2'; Caso a conta com o nome exista, não deve ser criado, pois não queremos mais de uma conta com o mesmo nome



    }
}
